language: php

sudo: false

php:
  - 8.0
  - 8.1

before_script:
  - composer config discard-changes true
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit --testdox tests
